# Default values for n8n.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: n8nio/n8n
  pullPolicy: IfNotPresent
  tag: "0.236.0-debian"

fullnameOverride: n8n

serviceAccount:
  roles:
    - apiGroups: ["argoproj.io"]
      resources: ["rollouts"]
      verbs: ["patch", "get"]

service:
  type: ClusterIP
  port: 5678

pvc:
  storage: 5Gi

ingress:
  enabled: true
  className: ""
  annotations: 
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: // your chatops endpoint
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: 
    - hosts:
        - // your chatops endpoint

istioIngress:
  enabled: false
  hostname: // your chatops endpoint

resources:
  requests:
    memory: 1Gi
    cpu: 100m
  limits:
    memory: 2Gi

nodeSelector: {}

tolerations: []

affinity: {}


### Database

postgres:
  resources:
    limits:
      cpu: 200m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 1Gi
  pvc:
    storage: 10Gi
    storageClassName: standard

