apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.fullnameOverride }}
  {{- if .Values.istioIngress.enabled }}
  namespace: istio-system
  {{- else }}
  namespace: {{ .Release.Namespace }}
  {{-  end }}
spec:
  {{- if .Values.istioIngress.enabled }}
  dnsNames:
    - {{ .Values.istioIngress.hostname }}
  {{- end }}
  {{- if .Values.ingress.enabled }}
    {{- with (first .Values.ingress.hosts) }}
  dnsNames:
    - {{ .host }}
    {{- end}}
  {{- end}}
  duration: 2160h0m0s
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-issuer
  renewBefore: 360h0m0s
  secretName: {{ .Values.fullnameOverride }}