{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    service: {{ .Values.fullnameOverride }}
  name: {{ .Values.fullnameOverride }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host:  {{ .host | quote }}
      http:
        paths:
        - backend:
            service:
              name: {{ $.Values.fullnameOverride }}
              port:
                number: {{ $.Values.service.port }}
          {{- range .paths }}
          path: {{ .path }} 
          pathType: {{ .pathType }}
        {{- end }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ $.Values.fullnameOverride }}
    {{- end }}  
  {{- end }}  
{{- end }}  