apiVersion: v1
kind: Secret
metadata:
  name: n8n-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  N8N_BASIC_AUTH_USER: ven-admin
  N8N_BASIC_AUTH_PASSWORD: {{ randAlphaNum 24 }}