kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql-pv
  namespace:  {{ .Release.Namespace }}
spec:
  storageClassName: {{ .Values.postgres.pvc.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.pvc.storage }}
