apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: {{ randAlphaNum 16 }}
  POSTGRES_DB: n8n
  POSTGRES_NON_ROOT_USER: n8n
  POSTGRES_NON_ROOT_PASSWORD: {{ randAlphaNum 16 }}